[build]
base = ""
publish = "build"

command = "npm run build"


# hmmm
[context.production]
  command = "npm run build:production"



[[plugins]]
package = "@netlify/plugin-lighthouse" # Installs Lighthouse Build plugin



[plugins.inputs.thresholds]
    performance = 0.5
    accessibility = 0.5
    best-practices = 0.5
    seo = 0.5
    pwa = 0.5


  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
