export const actionTypes = {
  CART_ADD: 'CART_ADD',
  CART_DELETE: 'CART_DELETE',
  CART_UPDATE: 'CART_UPDATE',
  CART_CLEAR: 'CART_CLEAR',
  CART_TOTAL_PRICE: 'CART_TOTAL_PRICE',
  CART_TOTAL_ITEMS: 'CART_TOTAL_ITEMS'
};
