name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  prettier:
    runs-on: ubuntu-latest
    
   

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Actual branch checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          fetch-depth: 0
          only_changed: True
          persist-credentials: false
          prettier_options: --write **/*.{js,md}    
      
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
