name: linux tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint the Commit Messages
      uses: wagoid/commitlint-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.FS_ECOMM_SECRET }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Lint Files
      run: npm run lint

    - name: Run Tests
      env:
        CI: true
      run: npm test